version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root_password # 루트 사용자 비밀번호 설정
      MYSQL_DATABASE: test_db # 생성할 기본 데이터베이스 이름
    ports:
      - '3308:3306' # 로컬 호스트의 3306 포트를 컨테이너의 3306 포트로 매핑
    command:
      [
        '--default-authentication-plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
  redis:
    image: redis:7.0
    container_name: redis-local
    ports:
      - '6388:6379' # 로컬 호스트의 6379 포트를 컨테이너의 6379 포트로 매핑
